### ISSUE TITLE
Improve find performance

### ISSUE THREAD

**Issue by Vorty** [tslenter/Cisco-DNA-Backup-Cleanup#2]
These lines here too a long time to run in my environment as there are huge amounts of subfolder and files:

        BCK_LIST3=$($FIND_LOC $BACKUP_LOC -name *$BCK_LIST2*)
        BCK_LIST4=$($FIND_LOC $BACKUP_LOC -type f -name *$BCK_LIST2*)

You can make this part almost instant by adding in -maxdepth 2, to make sure it doesnt go into all the sub directories.

        BCK_LIST3=$($FIND_LOC $BACKUP_LOC -maxdepth 2 -name *$BCK_LIST2*)
        BCK_LIST4=$($FIND_LOC $BACKUP_LOC -maxdepth 2 -type f -name *$BCK_LIST2*)

**Comment by tslenter** [comment]
Tested and works. Thanks for the update.
